# Generated by Django 5.0.4 on 2024-06-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TablaEjemplo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto_ejemplo", models.CharField(max_length=200)),
                ("fecha_ejemplo", models.DateTimeField()),
            ],
        ),
    ]
