# Generated by Django 5.0.4 on 2024-06-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("los4elementos", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TablaEjemplo",
        ),
    ]
