# Generated by Django 5.0.4 on 2024-06-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("los4elementos", "0009_asignatura"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="foto",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
