# Generated by Django 5.0.4 on 2024-06-27 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("los4elementos", "0010_estudiante_foto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estudiante",
            name="curso",
        ),
    ]
