# Generated by Django 5.0.4 on 2024-06-27 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("los4elementos", "0011_remove_estudiante_curso"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estudiante",
            name="foto",
        ),
        migrations.AddField(
            model_name="estudiante",
            name="curso",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="los4elementos.curso",
            ),
        ),
    ]
