# Generated by Django 5.0.4 on 2024-06-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("los4elementos", "0012_remove_estudiante_foto_estudiante_curso"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="foto",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
